version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.10.0-jessie
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - setup_remote_docker
      - run:
          name: Start prisma server
          command: |
            docker-compose -f prisma/docker-compose.yml up -d
            sleep 30
            docker ps
            curl -I http://localhost:4466
      - run:
          name: Deploy datamodel
          command: cd prisma && npx prisma deploy