version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.10.0-jessie
    steps:
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start prisma server
          command: |
            docker-compose -f prisma/docker-compose.yml up -d
            sleep 20
            docker ps