version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.10.0-jessie
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - setup_remote_docker
      - run:
          name: Start prisma server
          command: |
            ls -la
            docker info
            dockerd
            docker-compose -f prisma/docker-compose.yml up -d
            sleep 20
            docker ps