version: 2
jobs:
  build:
    machine: true
    image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Start Prisma Server
          command: |
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - > /dev/null
            sudo apt-get install -y nodejs
            sudo update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10
            node -v
            cd prisma
            docker-compose up -d
            docker ps
            cd ..
            npm install
            cd prisma
            npx prisma deploy
            npm run test