version: 2
jobs:
  build:
    machine: true
    image: node/10.11-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Start Prisma Server
          command: |
            node -v
            cd prisma
            docker-compose up -d
            docker ps
            cd ..
            npm install
            cd prisma
            npx prisma deploy
            npm run test