version: 2
jobs:
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start prisma server
          command: |
            docker-compose -f prisma/docker-compose.yml up -d
            sleep 20
            docker ps